name: Verifica Pull Request

on:
  pull_request:
    types: [opened, reopened, labeled, review_requested, assigned]

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checar labels
        uses: actions/github-script@v3
        with:
          script: |
            const pullRequest = github.context.payload.pull_request;
            if (pullRequest.labels.length === 0) {
              core.setFailed("Pull Request deve ter pelo menos um label.");
            }

      - name: Checar reviewers
        uses: actions/github-script@v3
        with:
          script: |
            const pullRequest = github.context.payload.pull_request;
            const reviewsRequested = pullRequest.requested_reviewers.length + pullRequest.requested_teams.length;
            if (reviewsRequested === 0) {
              core.setFailed("Pull Request deve ter pelo menos um reviewer.");
            }

      - name: Checar assignees
        uses: actions/github-script@v3
        with:
          script: |
            const pullRequest = github.context.payload.pull_request;
            if (pullRequest.assignees.length === 0) {
              core.setFailed("Pull Request deve ter pelo menos um assignee.");
            }
